/*!
 * @tago-io/builder
 * TagoIO (https://tago.io/)
 * TagoIO Builder V2.4.6 (https://git.io/JJ8Si)
 * 
 * Generated by     :: aikat
 * Generated at     :: 2020-10-29T06:29:12.750Z - UTC
 * Machine          :: DESKTOP-E6CUSHB - win32
 * Origin File      :: ..\..\TagoHelloWorld.js
 * Destination File :: ..\..\TagoHelloWorld.tago-io.js
 */
/******/ (function(modules) { // webpackBootstrap
/******/ 	// The module cache
/******/ 	var installedModules = {};
/******/
/******/ 	// The require function
/******/ 	function __webpack_require__(moduleId) {
/******/
/******/ 		// Check if module is in cache
/******/ 		if(installedModules[moduleId]) {
/******/ 			return installedModules[moduleId].exports;
/******/ 		}
/******/ 		// Create a new module (and put it into the cache)
/******/ 		var module = installedModules[moduleId] = {
/******/ 			i: moduleId,
/******/ 			l: false,
/******/ 			exports: {}
/******/ 		};
/******/
/******/ 		// Execute the module function
/******/ 		modules[moduleId].call(module.exports, module, module.exports, __webpack_require__);
/******/
/******/ 		// Flag the module as loaded
/******/ 		module.l = true;
/******/
/******/ 		// Return the exports of the module
/******/ 		return module.exports;
/******/ 	}
/******/
/******/
/******/ 	// expose the modules object (__webpack_modules__)
/******/ 	__webpack_require__.m = modules;
/******/
/******/ 	// expose the module cache
/******/ 	__webpack_require__.c = installedModules;
/******/
/******/ 	// define getter function for harmony exports
/******/ 	__webpack_require__.d = function(exports, name, getter) {
/******/ 		if(!__webpack_require__.o(exports, name)) {
/******/ 			Object.defineProperty(exports, name, { enumerable: true, get: getter });
/******/ 		}
/******/ 	};
/******/
/******/ 	// define __esModule on exports
/******/ 	__webpack_require__.r = function(exports) {
/******/ 		if(typeof Symbol !== 'undefined' && Symbol.toStringTag) {
/******/ 			Object.defineProperty(exports, Symbol.toStringTag, { value: 'Module' });
/******/ 		}
/******/ 		Object.defineProperty(exports, '__esModule', { value: true });
/******/ 	};
/******/
/******/ 	// create a fake namespace object
/******/ 	// mode & 1: value is a module id, require it
/******/ 	// mode & 2: merge all properties of value into the ns
/******/ 	// mode & 4: return value when already ns object
/******/ 	// mode & 8|1: behave like require
/******/ 	__webpack_require__.t = function(value, mode) {
/******/ 		if(mode & 1) value = __webpack_require__(value);
/******/ 		if(mode & 8) return value;
/******/ 		if((mode & 4) && typeof value === 'object' && value && value.__esModule) return value;
/******/ 		var ns = Object.create(null);
/******/ 		__webpack_require__.r(ns);
/******/ 		Object.defineProperty(ns, 'default', { enumerable: true, value: value });
/******/ 		if(mode & 2 && typeof value != 'string') for(var key in value) __webpack_require__.d(ns, key, function(key) { return value[key]; }.bind(null, key));
/******/ 		return ns;
/******/ 	};
/******/
/******/ 	// getDefaultExport function for compatibility with non-harmony modules
/******/ 	__webpack_require__.n = function(module) {
/******/ 		var getter = module && module.__esModule ?
/******/ 			function getDefault() { return module['default']; } :
/******/ 			function getModuleExports() { return module; };
/******/ 		__webpack_require__.d(getter, 'a', getter);
/******/ 		return getter;
/******/ 	};
/******/
/******/ 	// Object.prototype.hasOwnProperty.call
/******/ 	__webpack_require__.o = function(object, property) { return Object.prototype.hasOwnProperty.call(object, property); };
/******/
/******/ 	// __webpack_public_path__
/******/ 	__webpack_require__.p = "";
/******/
/******/
/******/ 	// Load entry module and return exports
/******/ 	return __webpack_require__(__webpack_require__.s = "../../TagoHelloWorld.js");
/******/ })
/************************************************************************/
/******/ ({

/***/ "../../TagoHelloWorld.js":
/*!*************************************************!*\
  !*** C:/Nimesa/Justrite/node/TagoHelloWorld.js ***!
  \*************************************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

eval("/*\r\n * TagoIO - Analysis Example\r\n * Hello World\r\n *\r\n * Check out the SDK documentation on: https://js.sdk.tago.io\r\n *\r\n * Learn how to send messages to the console located on the TagoIO analysis screen.\r\n * You can use this principle to show any information during and after development.\r\n*/\r\n\r\nconst { Analysis } = __webpack_require__(/*! @tago-io/sdk */ \"@tago-io/sdk\");\r\nconst { verifyInstall } = __webpack_require__(/*! ./include/JRUtils.js */ \"../../include/JRUtils.js\");\r\n\r\n// The function myAnalysis will run when you execute your analysis\r\nfunction myAnalysis(context, scope) {\r\n  // This will log \"Hello World\" at the TagoIO Analysis console\r\n  context.log(\"Hello World\");\r\n\r\n  // This will log the context to the TagoIO Analysis console\r\n  context.log(\"Context:\", context);\r\n\r\n  // This will log the scope to the TagoIO Analysis console\r\n  context.log(\"my scope:\", scope);\r\n  context.log(verifyInstall('from Tago Analysis'));\r\n}\r\n\r\n//module.exports = new Analysis(myAnalysis);\r\n\r\n// To run analysis on your machine (external)\r\nmodule.exports = new Analysis(myAnalysis, { token: \"836473c5-0b6b-4395-a342-e2629954ad0a\" });\r\n\n\n//# sourceURL=webpack:///C:/Nimesa/Justrite/node/TagoHelloWorld.js?");

/***/ }),

/***/ "../../include/JRUtils.js":
/*!**************************************************!*\
  !*** C:/Nimesa/Justrite/node/include/JRUtils.js ***!
  \**************************************************/
/*! no static exports found */
/***/ (function(module, exports) {

eval("var verifyInstall = function(parm) {\r\n\treturn \"Got parm: \" + parm;\r\n\t\r\n};\r\n\r\n//module.exports = verifyInstall;\r\nexports.verifyInstall = verifyInstall;\n\n//# sourceURL=webpack:///C:/Nimesa/Justrite/node/include/JRUtils.js?");

/***/ }),

/***/ "@tago-io/sdk":
/*!********************************************!*\
  !*** external "require(\"@tago-io/sdk\")" ***!
  \********************************************/
/*! no static exports found */
/***/ (function(module, exports) {

eval("module.exports = require(\"@tago-io/sdk\");\n\n//# sourceURL=webpack:///external_%22require(\\%22@tago-io/sdk\\%22)%22?");

/***/ })

/******/ });